# Generated by Django 5.2.8 on 2025-12-02 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NordstromFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(db_index=True, max_length=100)),
                ('filter_name', models.CharField(db_index=True, max_length=255)),
                ('filter_data', models.JSONField(default=dict)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('parent_category', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nordstrom_filters',
                'indexes': [models.Index(fields=['filter_type', 'filter_name'], name='nordstrom_f_filter__a00e43_idx'), models.Index(fields=['extracted_at'], name='nordstrom_f_extract_9d60fc_idx')],
                'unique_together': {('filter_type', 'filter_name')},
            },
        ),
        migrations.CreateModel(
            name='NordstromProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('in_stock', models.BooleanField(db_index=True, default=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('review_count', models.IntegerField(default=0)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nordstrom_products',
                'indexes': [models.Index(fields=['brand', 'category'], name='nordstrom_p_brand_15607b_idx'), models.Index(fields=['price'], name='nordstrom_p_price_eccf75_idx'), models.Index(fields=['scraped_at'], name='nordstrom_p_scraped_9d0f6a_idx'), models.Index(fields=['in_stock', 'category'], name='nordstrom_p_in_stoc_32aecf_idx')],
            },
        ),
    ]
