# Generated by Django 5.2.8 on 2025-12-04 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars/%Y/%m/%d/')),
                ('original_photo', models.ImageField(blank=True, null=True, upload_to='originals/%Y/%m/%d/')),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('dalle_revised_prompt', models.TextField(blank=True, null=True)),
                ('vision_description', models.TextField(blank=True, null=True)),
                ('openai_image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='api.avatarsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
