# Generated by Django 5.2.8 on 2025-12-04 06:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_avatarsession_generatedavatar'),
    ]

    operations = [
        
    ]
