# Generated by Django 5.2.8 on 2025-12-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_generatedavatar_openai_image_url_and_more'),
    ]

    operations = [

    ]
