# Generated by Django 5.2.8 on 2025-12-04 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_avatarsession_api_avatars_session_3dc016_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarsession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='avatarsession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='avatarsession',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='avatarsession',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='avatarsession',
            name='prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatarsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='avatarsession',
            table='avatar_sessions',
        ),
        migrations.DeleteModel(
            name='GeneratedAvatar',
        ),
    ]
