# Generated by Django 5.2.8 on 2025-12-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_avatarsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarsession',
            name='avatar_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatarsession',
            name='original_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
