# Generated by Django 5.2.8 on 2025-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_avatarsession_avatar_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarsession',
            name='original_avatar_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
