# Generated by Django 6.0 on 2026-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_avatarsession_original_avatar_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarsession',
            name='is_full_body',
            field=models.BooleanField(default=False),
        ),
    ]
