# Generated by Django 6.0 on 2026-02-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_amazonproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='coupon_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='delivery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='is_amazon_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='minimum_offer_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='original_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='sales_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
