# Generated by Django 6.0 on 2026-02-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_amazonproduct_coupon_text_amazonproduct_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarsession',
            name='latest_tryon_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
