"""
Django settings for shoppers_ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n0ubcpochsxu97w0154_++qyqbl*^vc96sqao^d9ql1ndz7$3k'
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
NANO_BANANA_PRO_API_KEY = os.getenv('NANO_BANANA_PRO_API_KEY')
PUBLIC_BASE_URL = os.getenv('PUBLIC_BASE_URL', 'http://localhost:8000')
IMGBB_API_KEY = os.getenv('IMGBB_API_KEY')
PIXELCUT_API_KEY = os.getenv('PIXELCUT_API_KEY')
PIXELCUT_BASE_URL = 'https://api.pixelcut.ai/v1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS - can be set via environment variable or defaults to allow all hosts
ALLOWED_HOSTS_ENV = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Allow all hosts - useful for development but should be restricted in production
    ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoppers_ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoppers_ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite')
if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Windows-specific configuration: Use 'solo' pool instead of 'prefork'
# This fixes PermissionError issues on Windows
import sys
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'
    # Alternative: use threads pool for better concurrency
    # CELERY_WORKER_POOL = 'threads'
    # CELERY_WORKER_CONCURRENCY = 4

from datetime import timedelta
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'scrape-nordstrom-products-daily': {
        'task': 'api.tasks.scrape_nordstrom_products',
        'schedule': timedelta(days=1), 
    },
    'refresh-amazon-products-every-2-hours': {
        'task': 'api.tasks.refresh_amazon_products',
        'schedule': timedelta(hours=2),
    },
    # Note: scrape_nordstrom_playwright_daily is now handled by Linux crontab
    # Use ./setup_scraping_cron.sh to set up the cron job
    # 'scrape-nordstrom-playwright-daily': {
    #     'task': 'api.tasks.scrape_nordstrom_playwright_daily',
    #     'schedule': crontab(hour=2, minute=0),
    # },
}


STATIC_URL = 'shoppers/static/'
STATIC_ROOT = BASE_DIR / "static/"

MEDIA_URL = 'shoppers/media/'
MEDIA_ROOT = BASE_DIR / "media/"

# Create media directories on startup
AVATAR_MEDIA_DIR = os.path.join(MEDIA_ROOT, 'avatars')
ORIGINAL_MEDIA_DIR = os.path.join(MEDIA_ROOT, 'originals')

os.makedirs(AVATAR_MEDIA_DIR, exist_ok=True)
os.makedirs(ORIGINAL_MEDIA_DIR, exist_ok=True)


# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
